### ISSUE TITLE
i can´t create a new branch to upload my company´s name

### ISSUE THREAD

**Issue by MatiHilu** [ugglr/Remote-Junior-Developer-jobs-directory#32]
I want to upload a new company where any dev can join their database and companys could check to hire devs.
The company is [Inclusion](https://inclusioncloud.com/)

**Comment by ugglr** [comment]
Hi there! thank you for your issue, do they offer remote positions?

**Comment by MatiHilu** [comment]
Hi! Thank you for replying
Yes, they offer remote positions

**Comment by MatiHilu** [comment]
How can i add this comany to the list?
Do you need more info about the company?

**Comment by ugglr** [comment]
I can help you add it, under what category should it be listed? under freelance?

**Comment by ugglr** [comment]
Hi I have made a PR wdyt? 
https://github.com/ugglr/Remote-Junior-Developer-jobs-directory/pull/33

**Comment by MatiHilu** [comment]
Thank you!!
Besides what you added, could you also add this? I am having toruble editing the files...

If creativity, cooperation and professional growth are part of your daily life, then you’re a perfect fit! We look for, develop and encourage inquisitive minds willing to work with cutting-edge technologies, who leverage the learning opportunities we have to offer and personify the supportive spirit that makes inclusion ideal for challenge seekers.

**Our Benefits**
-Flexibility
Work by goals, the schedule is yours.

-Work from wherever you want
You can work remotely or come to the office whenever you want

-Training and Development
Build your career with trainings and certifications. Select your job, live good experiences, train and grow!

-Language & Communication lessons
Improve the skills that will accompany you throughout your career.

-Choose your path
Our diversity of work naturally lends itself to new opportunities. You will have a vast number of projects available to develop in.

-Enjoy the ride
Work in a great environment guided by passion, inclusion and creativity.

**Comment by MatiHilu** [comment]
> I can help you add it, under what category should it be listed? under freelance?

It should be in Companies with Remote DNA

**Comment by ugglr** [comment]
Hi, I've merged the company into the list (#33). This repo is not serving more than a few lines of text per company, its purpose is to serve as a links directory where people can then read more on the respective sites. 

This, of course, is a philosophical question and maybe there could be added more, however, all of that information needs to be kept up to date and it's not something that I as a single maintainer can keep up with. 

Thanks for the issue 🎉

**Comment by MatiHilu** [comment]
Hello once again
First of all, thank you so much for all the work, i really apreciated it

I have only one think to modificate.
The name of the Company is "Inclusion Cloud"
Not only inclusion. It was my foult becouse i gave you the name Inclusion only.

Cloud you please modify it once more?

**Comment by ugglr** [comment]
> Hello once again First of all, thank you so much for all the work, i really apreciated it
> 
> I have only one think to modificate. The name of the Company is "Inclusion Cloud" Not only inclusion. It was my foult becouse i gave you the name Inclusion only.
> 
> Cloud you please modify it once more?

Hi, no problem, I will change it soon 👍

**Comment by MatiHilu** [comment]
Hi, how are you?
Thanks for the changes!!
I saw that the website now has changed styles, i like it!!!

I write once more to ask if you wolud change the rel="noreferrer" attribute on the website for inclusion cloud?

**Comment by ugglr** [comment]
> Hi, how are you? Thanks for the changes!! I saw that the website now has changed styles, i like it!!!
> 
> I write once more to ask if you wolud change the rel="noreferrer" attribute on the website for inclusion cloud?

Hi there!
Thanks for the feedback, I have target="_blank" for all links so they open in a new window, therefore it's a security risk not to include the rel="noreferrer" flag. 

Why don't you want it included?

**Comment by MatiHilu** [comment]
It’s important for us because it would improve the domain authority of our website.
We can share with you this links to show you that you can trust us:
https://inclusioncloud.com/development-certifications/
https://inclusioncloud.com/corporate-certifications/
https://inclusioncloud.com/awards-and-recognitions/
https://www.linkedin.com/company/inclusioncloud/
https://clutch.co/profile/inclusion-cloud
https://www.glassdoor.com/Overview/Working-at-Inclusion-Cloud-EI_IE2794333.11,26.htm
https://g.page/InclusionCloud

Please check this links to know us better.
We hope that with certificates, awards, recognitions and our location you can trust us and consider the removal of the rel="noreferrer" flag for us.
Thank you.
I will be waiting for your reply.

**Comment by ugglr** [comment]
> It’s important for us because it would improve the domain authority of our website. We can share with you this links to show you that you can trust us: https://inclusioncloud.com/development-certifications/ https://inclusioncloud.com/corporate-certifications/ https://inclusioncloud.com/awards-and-recognitions/ https://www.linkedin.com/company/inclusioncloud/ https://clutch.co/profile/inclusion-cloud https://www.glassdoor.com/Overview/Working-at-Inclusion-Cloud-EI_IE2794333.11,26.htm https://g.page/InclusionCloud
> 
> Please check this links to know us better. We hope that with certificates, awards, recognitions and our location you can trust us and consider the removal of the rel="noreferrer" flag for us. Thank you. I will be waiting for your reply.

I did some reading, and I think you are right, there are some benefits on my end as well to remove the flag for my links. 

I've already merged the changes 👍 should be in production by the time you see this.
