### ISSUE TITLE
Backend Technology and Dynamic career links

### ISSUE THREAD

**Issue by Junaid300** [ugglr/Remote-Junior-Developer-jobs-directory#48]
I need to ask few things.
- What backend are you using ? I think this is static one. Am I right?
- Careers or freelancing site links are static. We should move it to dynamic (Just a suggestion)
- There should be contribute guidance file and stack information
I am interest in contribute to this. Is there any discord or slack for this oos ?

**Comment by ugglr** [comment]
Hi there 👋
Thank you for your interest in the project. 

I think the contribution guidance is good, I should add one of those. 

For the other two, I have this comment 👇
Before discussing the architecture I would like to ask about the feature you are missing, and what value it brings.

**Comment by Junaid300** [comment]
> ng the architecture I would like to ask about the feature you are missing, and what value it brings.

Everything is static in this project, If we think about a long goal there gonna be hundreds and thousands of URLs and it gonna be hard to manage them on front end. There should a separate small app or a option where we can add information about careers, freelancing and other stuff. We need to add  a backend too. It will help us to manage bundle of stuff. And currently everything appears when we load the page like freelancers and there should lazy loading and searching option for this. 
this is what i have in my mind
I hope you understand my point

**Comment by ugglr** [comment]
I see that you mention one feature about search, that is a good one and I'm working on filtering currently.

I don't want to introduce complexity when it comes to managing the content. External database might be interesting for some kind of feature, but before that gets introduced, it needs to be clearly specified why and what value that brings to a user.

I want it to be possible for anyone to make a PR for updating the content. For that to be possible, the data needs to be stored inside of the repo. The content should be curated by the community and moderated through GitHub out in the open.

**Comment by Junaid300** [comment]
Please add contribution guideline.

To be honest, I don't like managing everything on frontend with hardcode data.  It will not be helpful for the user but it can improve our site performance.  For example, we have added a site `abc.com` in freelance list. And all of sudden `abc.com` banned so what we will do ? it will redirect to domain not found.  What will do is remove from our static data right?  This is what i had in my mind for this feature.

I will clone the project and create a PR. but for what feature ? as you said you are already implementing filter and searching functionality.

**Comment by ugglr** [comment]
Hi Thank you for your patience, 
I've decided to close-source the commercial project of this repo. I've left all the resources intact and available for everyone to access. This is what most starred the repo for. There's just too much sensitive data that needs to be handled for the project to be open-sourced.
Thanks again
