### ISSUE TITLE
Fix post template

### ISSUE THREAD

**Issue by ugglr** [ugglr/Remote-Junior-Developer-jobs-directory#5]
The post template needs to be tweaked to fit the layout of a generic job post. 

Things that come to mind: 
- apply button at the end of the post.
- Place for company logo, and website link.

**Comment by ugglr** [comment]
Hi @koolamusic !

**Comment by anthonyhi11** [comment]
I'd like to take a crack at this

**Comment by koolamusic** [comment]
aha!!

Did I make a commitment to this issue, sorry if I didn't follow up.
This project could really be useful now.

How can I help?
I'm open to skypes too.

**Comment by ugglr** [comment]
> aha!!
> 
> Did I make a commitment to this issue, sorry if I didn't follow up.
> This project could really be useful now.
> 
> How can I help?
> I'm open to skypes too.

Hi! Thank you for your comment XD  I'm going to be honest and say I have not touched this project in more than a year, but recently it's been gaining a bit of stars, which communicates that there's a hunger for this type of information. 

I think the floor is completely open right now. If someone sees this and have some ideas of what we could do here it would be awesome to hear about it!

My initial idea was to have this be an open source job board for remote junior positions, and this issue would be the template everyone could initially copy for making new posts.

**Comment by koolamusic** [comment]
I have an Idea and we can use Airtable as a database and still leverage the Architecture we have.

Also Who would be posting the jobs and curating them too?
