### ISSUE TITLE
Make a better boilerplate post

### ISSUE THREAD

**Issue by ugglr** [ugglr/Remote-Junior-Developer-jobs-directory#6]
It would be helpful to create a post of a fake listing which can be copied by the companies who want to post a job. 

Benefits. 
1. Job poster does not need any prior knowledge on how to create posts in markdown. 
2. If widely used the posts will look more or less the same, making it easier for job searchers to extract information from the post. Since they know where to look. 
3. The time needed to create a post dramatically decreases. 

In the future, it would be great to implement a tag system, and being able to filter jobs.

**Comment by ugglr** [comment]
Hi @koolamusic !

**Comment by koolamusic** [comment]
Thanks for the mention, How would this template be designed, what format do you need prospective orgs to submit their listing in

**Comment by ugglr** [comment]
Thank you for the engagement! 

I'm thinking of sticking to something that is very familiar in this space as the screencaps below from Weworkremotely, or remotive. 

What do you think of that vision of the future?

![screencapture-remotive-io-remote-jobs-software-dev-ios-developer-15705-2019-06-16-00_50_40](https://user-images.githubusercontent.com/5120880/59554115-0832e200-8fd1-11e9-894a-1458d5697724.png)
![screencapture-weworkremotely-remote-jobs-stack-builders-experienced-front-end-developer-in-javascript-2019-06-16-00_51_27](https://user-images.githubusercontent.com/5120880/59554116-08cb7880-8fd1-11e9-851f-ba11110fda7a.png)

**Comment by koolamusic** [comment]
I think moving from the known to unknown is a great approach, meanwhile, I would have some spare time by next week and take a look at implementing stuff

**Comment by ugglr** [comment]
Sounds awesome!
