### ISSUE TITLE
API section is out of screen

### ISSUE THREAD

**Issue by newstler** [ugglr/Remote-Junior-Developer-jobs-directory#73]
This is on my MacBook Pro 14":

<img width="1352" alt="Снимок экрана 2024-08-15 в 14 47 04" src="https://github.com/user-attachments/assets/3efa8cd2-592c-47c5-8fa8-b5fff5ac180e">

**Comment by ugglr** [comment]
Many thanks for the issue! I've fixed it now 🤓
